# Generated by Django 6.0 on 2026-03-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_remove_booking_end_date_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='kinsman_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='kinsman_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='kinsman_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
