# Generated by Django 6.0 on 2026-03-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_booking_amount_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driver_upkeep',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra daily cost applied after day 1', max_digits=10),
        ),
    ]
