# Generated by Django 6.0 on 2026-03-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_multi_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='overtime_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base price for 0 Day (5 hours Max)', max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per hour for every hour past 5 hours', max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='driver_upkeep',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra daily cost applied in multi-day rentals', max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Daily Rental Price', max_digits=10),
        ),
    ]
