# Generated by Django 6.0 on 2026-03-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_booking_is_multi_day_booking_overtime_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a picture of the car', null=True, upload_to='cars/'),
        ),
    ]
